layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: CFD
    web_url: https://github.com/topics/cfd

  - name: Turbulent Combustion
    web_url: https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=turbulent+combustion&btnG=  

  - name: Two-Phase Reacting Flows
    
  - name: Fortran
    web_url: https://github.com/topics/fortran

  - name: Python
    web_url: https://github.com/topics/python

  - name: LaTex
    web_url: https://github.com/topics/latex

repositories:
  - NUAA-Beamer
  - SpotifyLyrics
  - indentLine
  - pyPlot3d
  - ssr-qrgen
  - ssgo_arukas
