layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pinned
  # sort_by options:
  #   - pushed
  #   - stars
  #   - pinned
  pinned_repos:
    - NUAA-Beamer
    - SpotifyLyrics
    - indentLine
    - pyPlot3d
    - ssr-qrgen
    - ssgo_arukas
  limit: 6
  exclude:
    forks: false
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # linkedin: your_username
  # medium: @your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: ztnuaa
  # youtube: your_username
  instagram: timo_zhang
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url

topics:
  - name: CFD
    web_url: https://github.com/topics/cfd
    image_url: https://i.imgur.com/C1YVeQJ.png

  - name: Turbulent Spray Combustion
    web_url: https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=turbulent+spray+combustion&btnG=  
    image_url: https://i.imgur.com/vOS7lZH.png

  - name: Large Eddy Simulation
    web_url: https://www.sciencedirect.com/topics/earth-and-planetary-sciences/large-eddy-simulation
    image_url: https://i.imgur.com/Gfi86oP.png
    
  - name: Fortran
    web_url: https://github.com/topics/fortran
    image_url: https://cdn.rawgit.com/file-icons/source/master/svg/Fortran.svg

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png

  - name: LaTex
    web_url: https://github.com/topics/latex
    image_url: https://raw.githubusercontent.com/github/explore/8301424c613f4cd048e8a7f3e3c81ea20321f3ed/topics/latex/latex.png

repositories:
  - NUAA-Beamer
  - SpotifyLyrics
  - indentLine
  - pyPlot3d
  - ssr-qrgen
  - ssgo_arukas
